version: "1"
services:
  neo4j:
    image: neo4j:4.4.4-enterprise
    hostname: neo4
    container_name: neo4ForCrudTest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/Mehdi
      NEO4J_dbms_logs_debug_level: DEBUG
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"